/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:b86a15ab-92b3-4549-bcd3-37580ac6d87d",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_77qO9F9Si",
    "aws_user_pools_web_client_id": "3ovc51qug3nmuc5susjf8qe0d8",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://5g7ebnvivvac3gioqicid2ei4m.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "name-dev",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
